In [68]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
np.array(A)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [69]:
np.array(B)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [75]:
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [84]:
multi_array = np.dot(A, B)
multi_array.max()

np.int64(47)